added linked progress plot
sbailey/surveyqa pull request #23
Opened 2019-03-16 05:17 UTC by williyamshoe

added linked vertical line that shows up on both progress plots

2019-03-16 17:59 UTC, sbailey requested changes
Overall looks good.  Minor requests inline.

2019-03-16 17:59 UTC, sbailey commented on py/surveyqa/summary.py
> +console.log(x);
Please remove the leftover debugging `console.log()` calls.

2019-03-16 17:59 UTC, sbailey commented on py/surveyqa/summary.py
> +'''
Please add a few comment to the above `line_source` and `js` code about what this does and why (target audience: a new collaborator reading this code 2 years from now and wanting to match up the code she is reading to the visual elements on the page).

2019-03-18 05:32 UTC, williyamshoe commented
Alright; I removed the debugging logs and added comments to describe what the js code and the line_source did. I also shortened the js code a bit by removing an unnecessary for loop.

2019-03-18 05:46 UTC, sbailey approved these changes

2019-03-18 05:46 UTC, sbailey commented
Looks good; thanks.  Merging now.

2019-03-18 05:46 UTC, merged