added moon location as black dot
sbailey/surveyqa pull request #39
Opened 2019-04-01 00:45 UTC by rdoshi99

- added function get_moonloc which returns a SkyCoord object  to retrieve the RA and DEC for the moon
- plotted the location as a black dot on the skypath plot
- the coordinates seem a little off
- still working on the phase of the moon
- in progress issue #27

2019-04-01 06:10 UTC, sbailey requested changes
A few comments/requests inline.  Minor merge conflicts have arisen which could be resolved by the github web editor followed by "git pull" on your local copy.

2019-04-01 06:10 UTC, sbailey commented on py/surveyqa/nightly.py
> +    mjd_midnight = int(exposures['MJD'][0])
int(MJD) is midnight in Greenwich, England, instead of midnight at Kitt Peak in Arizona (7 hours behind GMT/UT/UTC).  `int(exposures['MJD'][0])` is also fragile since it depends upon whether the first exposure of the night was before or after 5pm local time (i.e. before or after midnight UT).  This might be the source of your "the coordinates seem a little off", depending upon what you were comparing against.

Consider parsing the "NIGHT" column (YEARMMDD of the sunset) into the MJD of local midnight instead.

Check the case of night 20191215 by hand.  It looks like our bright time exposure path got very close to the moon, which shouldn't happen (it could be a bug in the scheduler, or in the moon location calculation).  Compare with the `MOONSEP` and `MOONFRAC` values for that night (which also could have bugs, so approach with some skepticism and let's track this down).

2019-04-01 06:10 UTC, sbailey commented on py/surveyqa/nightly.py
> +def get_moonloc(mjd_midnight):
Detail: although you intend to use this function by calling it with the MJD of a particular midnight, it actually works to return the moon location at any MJD whether or not it was midnight.  i.e. it would be better for this function to be just `get_moonloc(mjd)` (valid for any MJD) or `get_moonloc(night)` (forcing the answer to be for midnight on a particular night=YEARMMDD of sunset).

2019-04-01 06:10 UTC, sbailey commented on py/surveyqa/nightly.py
> +    fig.circle(ra, dec, size=10, color='black')
Minor: let's make the moon color "gold" and pick a different color for the start-of-night star symbol.

2019-04-04 08:53 UTC, rdoshi99 commented
- changed moonloc function to parse the night instead
- changed moon color to gold and orange for the start-of-night star
- checked the case of 20191215 by hand, found that for the tiles near the moon, the moon separation angle is only 5 degrees

2019-04-04 18:11 UTC, sbailey requested changes

2019-04-04 18:11 UTC, sbailey commented on py/surveyqa/nightly.py
> +    t_midnight = Time(iso_format, format='iso') + 24*u.hour
Almost.  This is midnight GMT, but we want midnight in Arizona after the sunset on night YEARMMDD.  Midnight in AZ is 7am GMT on the next day, so you are correct about the `+ 24*u.hour`, but we need the time portion of the string to be `07:00:00` not `00:00:00`.  Double check me on that...

2019-04-05 18:03 UTC, sbailey approved these changes

2019-04-05 18:04 UTC, merged