readded hover for summary skyplot
sbailey/surveyqa pull request #53
Opened 2019-04-09 05:10 UTC by williyamshoe

addresses #46

2019-04-10 06:01 UTC, sbailey requested changes
Thanks for (re-)adding this.  I've put comments inline, in two categories:
* feature requests (using NIGHT instead of MJD, additional info in tooltip)
* more robustness for future inputs (not assuming TILEID=-1 is the only non-standard tile, not assuming that input tiles are sorted by TILEID).

Details inline.

2019-04-10 06:01 UTC, sbailey commented on py/surveyqa/summary.py
> +    tiles_unique, indx = np.unique(exposures['TILEID'], return_index=True)
Good use of `return_index` to simultaneously get sorted list of TILEIDs and list of indices needed to sort other columns of `exposures` to match.

2019-04-10 06:01 UTC, sbailey commented on py/surveyqa/summary.py
> +    nights = nights[1:len(nights)]
Trimming off the first element here assumes that there is a single TILEID that isn't in the list of tiles (presumably -1, from calib exposures in these example files).  That could break in the future if the input exposure list didn't have any calibs, or used different negative TILEIDs for different types of calibs.

Better to first filter `exposures` to just the tiles in the tiles list before proceeding with the `np.unique` and sorting, e.g.
```python
#- remove calib or other observations that don't match tiles
keep = np.in1d(exposures['TILEID'], tiles['TILEID'])
exposures = exposures[keep]
```

2019-04-10 06:01 UTC, sbailey commented on py/surveyqa/summary.py
> +    nights = exposures['MJD'][indx]
Let's use the "NIGHT" column instead of the "MJD" column for the tooltip.

2019-04-10 06:01 UTC, sbailey commented on py/surveyqa/summary.py
> +        EXPID = exposures_id
Since the `nights_int` and `exposures_id` columns are sorted by TILEID when constructed, this code here is also implicitly assuming that the input `tiles` table is also sorted by TILEID, which it may not be.  At the start of this function, explicitly sort `tiles` by TILEID without modifying the original:
```python
tiles = Table(np.sort(tiles, order='TILEID']))
```

2019-04-10 06:01 UTC, sbailey commented on py/surveyqa/summary.py
> +                ("1ST EXP MJD", "@MJD")
Please also add the "PROGRAM" and "PASS" columns from the tiles table to the tooltip.  If bokeh has an option to reduce the fontsize of the tooltip, that might be necessary to reasonably display all these fields.  In a previous comment I requested replacing MJD with NIGHT; that could be combined with EXPID, e.g. "1ST NIGHT/EXPID" to be on a single row, and "PROGRAM/PASS".

Context: The DARK and BRIGHT programs have multiple "passes", where we repeat the same piece of sky with a different TILEID to pick up additional targets.  Usually we would finish lower pass numbers before higher pass numbers within a program, so seeing that is useful for determining if we are almost done with a given patch of sky.

2019-04-12 07:04 UTC, williyamshoe commented
Thanks for the comments! I've implemented the changes listed above. Also, I'm unsure if I can shrink the hovertool box anymore than I have in this new commit.

2019-04-14 04:30 UTC, sbailey approved these changes

2019-04-14 04:34 UTC, sbailey commented
Looks good.  Thanks for the updates.  The hover tooltip size looks good -- compact while still being readable.

2019-04-14 04:34 UTC, merged