Linking file branch
sbailey/surveyqa pull request #64
Opened 2019-04-24 05:31 UTC by williyamshoe

Generates a linking.js, then in each html nightly file, references this file to create the previous, next, last, and first links. 
linking.js is generated within core.py, and can accommodate if a subset is given. This branch builds off of #54.

2019-04-29 05:34 UTC, sbailey requested changes
I added some comments inline.  Some of them about overly generic variable and function names could be addressed, and then let's chat as a group about how to handle the first/last night prev/next links with this PR compared to PR #63.

2019-04-29 05:34 UTC, sbailey commented on py/surveyqa/core.py
> +        fp.write("get_dict({})".format(str(file_js)))
This seems a little magical to me.  Is it relying upon the fact that python dictionaries represented as strings are extremely similar to json?  I think they differ by single vs. double quote usage and browsers might be forgiving of that, but better to use `json.dumps(file_js)`.  Or maybe I'm completely missing how this works.

2019-04-29 05:34 UTC, sbailey commented on py/surveyqa/core.py
> +    generate_js(outdir, nights_sub, nights != None)
Please use a more descriptive function name than `generate_js`.  Generate js for what?

2019-04-29 05:34 UTC, sbailey commented on py/surveyqa/nightly.py
> +
I think these two were removed by an earlier PR and are accidentally being added back in.  Double check that they aren't used anymore and remove from this PR if possible.

2019-04-29 05:34 UTC, sbailey commented on py/surveyqa/nightly.py
> +
I resolved merge conflicts, but there is a "how should we do it" conceptual conflict with the previously merged PR #63 .  I left both in here and let's chat as a group on Monday for how to handle the navigation links for the first and last nights in light of this PR method.

2019-04-29 05:34 UTC, sbailey commented on py/surveyqa/nightly.py
> +        function get_dict(dict) {
Please use a more descriptive name.   get dict for what?  Input dict is what?  It looks like this function is setting navigation elements, not getting a dictionary.  Please add comments in script about what is does, what the input should be, etc., similar to the type of information we include with python docstrings.

2019-05-05 20:25 UTC, williyamshoe commented
I think I fixed all the issues above, and I have added the function where a link are un-clickable if there is no previous/next link.

2019-05-06 22:56 UTC, sbailey approved these changes

2019-05-06 23:01 UTC, sbailey commented
Thanks.  Works well.  I renamed `generate_js_containing_json_file` to the slightly more informative (to me) name `write_night_linkage`.  i.e. trying to give a hint about the meaning of the contents (night linkage) rather than the format details (js containing json, which could be anything).

2019-05-06 23:01 UTC, merged